language: node_js
node_js:
- 10

before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn install

branches:
  only:
  - master

cache:
  yarn: true
  directories:
  - node_modules

jobs:
  include:
    - stage: npm publish
      before_script:
        - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      script:
        - yarn build
        - npm publish
    - stage: document
      script:
        - yarn docs:build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local-dir: docs/.vuepress/dist
        on:
          branch: master
        target-branch: gh-pages

notifications:
  email: false
  slack:
    rooms:
      - glriaroom:GJpK4bqmhqF9CtV1l4qVSp6Q#devops
    on_success: change # default : always
    on_failure: always # default : always
