language: node_js
node_js:
- "10"

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn -v
  - git config user.name "gloria"
  - git config user.email "pureainu@gmail.com"

install:
  - yarn install

script:
  - yarn build
  - yarn styleguide:build

after_success:
  - gh-pages -d /home/travis/build/gloriaJun/glria-vuejs-ui/node_modules/vue-cli-plugin-styleguidist/styleguide
  - npm publish

deploy:
  provider: npm
  email: pureainu@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: false