language: node_js
node_js:
- "10"

branches:
  only:
    - master

install:
  - npm install

jobs:
  include:
  - stage: npm publish
    before_script:
      - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    script:
      - npm run build
      - npm publish
  - stage: document
    script:
      - npm run styleguide:build
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      local-dir: dist-doc
      on:
        branch: master
      target-branch: gh-pages
