language: node_js
node_js:
- "10"

branches:
  only:
    - master

before_install:
  - git config user.name "gloria"
  - git config user.email "pureainu@gmail.com"
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN

install:
  - npm install

jobs:
  include:
  - stage: npm publish
    script:
      - npm run build
      - npm publish
  - stage: document
    script:
      - npm run styleguide:build
      - gh-pages -d node_modules/vue-cli-plugin-styleguidist/styleguide

