language: node_js
node_js:
- "10"

branches:
  only:
    - master

install:
  - npm install

jobs:
  include:
  - stage: npm publish
    before_script:
      - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
    script:
      - npm run build
      - npm publish
  - stage: document
    script:
      - npm run styleguide:build
      - cd node_modules/vue-cli-plugin-styleguidist/styleguide
      - git init
      - git add -A
      - git commit -m 'deploy'
      - git push -f https://${GITHUB_TOKEN}github.com/gloriaJun/glria-vuejs-ui.git master:gh-pages
