language: node_js
node_js:
- 10

# Install specific version
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
- export PATH="$HOME/.yarn/bin:$PATH"

install:
- yarn install

branches:
  only:
    - master

# $HOME/.cache/yarn
cache:
  yarn: true

jobs:
  include:
    - stage: npm publish
      before_script:
        - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
      script:
        - yarn build
        - npm publish
    - stage: document
      script:
        - yarn styleguide:build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local-dir: dist-doc
        on:
          branch: master
        target-branch: gh-pages

notifications:
  slack: glriaroom:$SLACK_TOKEN