language: node_js
node_js:
- "10"

branches:
  only:
    - master

before_install:
  - git config user.name "gloria"
  - git config user.email "pureainu@gmail.com"

install:
  - npm run install

script:
  - npm run styleguide:build
  - gh-pages -d node_modules/vue-cli-plugin-styleguidist/styleguide

jobs:
  include:
  - stage: npm release
    script:
      - echo "Deploying to npm ..."
      - npm run build
    deploy:
      provider: npm
      email: pureainu@gmail.com
      api_key: $NPM_TOKEN
      skip_cleanup: true
      on:
        tags: true

